# Generated by Django 5.1.7 on 2025-03-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_security_app', '0002_remove_worker_title_worker_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[
            ],
        ),
    ]
