# Generated by Django 5.1.7 on 2025-03-27 12:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_security_app', '0003_alter_worker_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='worker',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
